# Generated by Django 4.2.6 on 2023-11-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
