# Generated by Django 4.2.6 on 2023-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
